# Fundamental Hardware Support
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y

# Enable Logging to resolve Kconfig warnings
CONFIG_LOG=y

# Base Modbus configuration
CONFIG_MODBUS=y
CONFIG_MODBUS_SERIAL=y

# SPI and GPIO
CONFIG_SPI=y
CONFIG_GPIO=y

CONFIG_MIPI_DBI=y

# Display Drivers
CONFIG_DISPLAY=y
CONFIG_ST7735R=y

# If you want to use the high-level graphics library
CONFIG_LVGL=y
# Increase main stack size (Default is often 1024, which is too small for LVGL)
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_LV_Z_SHELL=y
