# Fundamental Hardware Support
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y

# Enable Logging
CONFIG_LOG=y

# Base Modbus configuration
CONFIG_MODBUS=y
CONFIG_MODBUS_SERIAL=y

# Adjust stack size if necessary (can be lowered now that LVGL is gone)
CONFIG_MAIN_STACK_SIZE=1024