# Fundamental Hardware Support
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y


# Enable Logging
# Enable the logging subsystem
CONFIG_LOG=y
#CONFIG_LOG_MODE_DEFERRED=y  # Buffers logs to avoid blocking threads
CONFIG_LOG_MODE_IMMEDIATE=y #temp
# 3 = Info, 4 = Debug
CONFIG_LOG_DEFAULT_LEVEL=3

# Enable Serial and Interrupt Driven API (Required for Modbus)



# Nordic specific UART driver
CONFIG_UART_NRFX=y

# Enable the Modbus stack and Serial (RTU/ASCII) backend
CONFIG_MODBUS=y
CONFIG_MODBUS_SERIAL=y
# Enable verbose raw packet logging
CONFIG_MODBUS_LOG_LEVEL_DBG=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Flash and QSPI drivers
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FCB=y
# This is crucial for the flash_area_write function
CONFIG_FLASH_PAGE_LAYOUT=y
